### ISSUE TITLE
Jade support

### ISSUE THREAD

**Issue by PEM--** [ccorcos/meteor-compile-view#1]
Amazing package :clap:. A pure relief to avoid switching from one file to the other just for adding a field.

Would you be kind enough to add Jade capabilities to it?

**Comment by ccorcos** [comment]
I want to but its honestly quite a pain in the ass to do that. It would be great if I could `api_use` the jade package and just use their compilation but currently, I'd have to copy over all of their code and hook it into mine. Thats actually what I had to do with the HTML and the build in `templating` package.

Its kind of a pain in the ass that I can't just do addHtml, addJade, addCoffee, addLess, etc. using other packages compile steps.

**Comment by PEM--** [comment]
You're right. It would be terrible pain in the ass. There is currently some stuff in preparation for the 0.9.4 that could help us a lot. Build plugins are going to be named. Therefore, we could leverage the work of Maxime Quandalle on Jade, and the work of Meteor on CoffeeScript integration.

Still, I'm not sure about what Meteor will do when you want to set your tasks in a proper order of compilation. I'm not even sure that this is foreseen.

Anyway, you are paving the way for a better integration of our views. Your idea just rocks.

**Comment by ccorcos** [comment]
really? Thats exactly what I was looking for! I'll keep my eyes peeled when 0.9.4 comes around.

Thanks

**Comment by bengott** [comment]
Did you get a chance to circle back to this issue? And did the build plugin stuff make this possible?

**Comment by ccorcos** [comment]
I haven't touched this since I made it.

I haven't seen any build plugin stuff. Can I do addJade() yet?

**Comment by bengott** [comment]
I haven't messed with it yet myself, but this looks promising:
https://docs.meteor.com/#/full/Package-registerBuildPlugin
https://docs.meteor.com/#/full/Plugin-registerSourceHandler

**Comment by ccorcos** [comment]
I see. Doesn't look like its been implemented yet on many packages though:

https://github.com/meteor/meteor/blob/devel/packages/coffeescript/plugin/compile-coffeescript.js

**Comment by avalanche1** [comment]
Hey, Chet!
Has there been any progress with advent of Meteor 1.0?
I was dreaming of putting all my related component code into one file.
I use Jade, Coffee and Stylus, btw)

**Comment by ccorcos** [comment]
haha I'm so down @avalanche1. I've even thought of putting everything in your code base in one giant file. Then you can compile and view the code based on anchors. For example, when you write code, I often find myself jumping between files. Instead, what if you could write all of that stuff in the same place, in the order in which you build everything.

Just imagine, creating a view component, writing code in the following places:

```
~home.server.js
~home.client.js
~home.md
~home.html
~home.css
~user.html
~user.css
~user.client.js
~home.html
~home.css
~utils.js
~home.client.js
~home.html
~home.css
```

This is the compile order when files are concatenated and output. You can understand how everything was built by starting at the top and working your way down the page, and you no longer have to pain yourself with load order. But you can also filter by tags very intuitively and code within different sections this way, opening up multiple tabs if you wish. You could even do things like home.html,home.css to see all the home component's html and css interlaced.

I'd love to pursue this more, but I lack time and expertise. I've never built a syntax highlighter, let alone an atom package. I think this would be 1-2 day project for someone familiar with atom. I could definitely build the Meteor transpiler if someone makes nice editor tools :)

**Comment by ccorcos** [comment]
You know anyone who knows how to build a package for Atom.io?

https://discuss.atom.io/t/unified-file-editing/19453

**Comment by avalanche1** [comment]
Ahh... honestly I didn't understand half of the last paragraph)
Why are you talking syntax highlighting here? I think it's build process we're talking.
Figure we need a transpiler that will grab sections of code, determine their language and send them to appropriate compiler.
Syntax highlighting is in the end of tasklist, imo.
And load order is a whole other thing - needs to hook into meteor buid process itself.
ps. I'm working in Webstorm

**Comment by ccorcos** [comment]
well I build this and it works -- its just no fun to use without dev tools that recognize it. I'm at the point where I don't want to put more time into this unless theres proper highlighting. 

My point in the last paragraph is this: there is one canonical file with different sections for different types of code. all the code of the same type is pulled out in order of this file and compiled together.

Then, using the different tags, we can filter / query different sections of this big file so we can break it up into pieces. I can query 'home.html' and get all the home.html sections concatenated and edit those sections separately in a new file. I can query just "html" and see all the html sections, etc.

The problem with jade support is this: Meteor's build tool doesnt allow me to transpile jade into html, and dump the html right into the existing build system -- I have to copy all their html parsing code 

https://github.com/ccorcos/meteor-compile-view/blob/master/ccorcos:view.js#L54

So thats ugly and not exactly scalable.

**Comment by avalanche1** [comment]
Can't we hook up into build process to be the first transpiler in queue, and just cut our file into three separate files, like .jade, .coffee & .styl. And then let the appropriate transpiler do their work transpiling these three files into their appropriate languages?

**Comment by ccorcos** [comment]
> Can't we hook up into build process to be the first transpiler in queue, and just cut our file into three separate files, like .jade, .coffee & .styl. And then let the appropriate transpiler do their work transpiling these three files into their appropriate languages?

Maybe thats a new feature -- I built this a while ago, and back then, this wasn't possible.

**Comment by ccorcos** [comment]
I elaborated on my idea here: https://github.com/ccorcos/unified-file

Its an evolved version of this idea.

**Comment by avalanche1** [comment]
So... you have a working initial transpiler. Do you know how to hook it into Meteor build process?

**Comment by ccorcos** [comment]
sorta. You have to use registerBuildPlugin, but its not documented

https://github.com/ccorcos/meteor-compile-view/blob/master/package.js#L11

**Comment by crapthings** [comment]
i'm from here

https://github.com/ManuelDeLeon/viewmodel/issues/213#issuecomment-203185061

https://github.com/mquandalle/meteor-jade

https://github.com/mquandalle/meteor-stylus

this one handle viewmodel with jade more elegant

https://github.com/dalgard/meteor-jade

+1 jade coffeescript stylus and blaze

**Comment by ccorcos** [comment]
@crapthings do it! PR's welcome
